grant all on traffic.* to 'root'@'%' identified by 'bigDataTeam' with grant option;
	
create table zc_driver_train(
sfzh   varchar(50),
jl    int(11),
zt   int(11),
ryzt   int(11),
max_wfxw   int(11),
level1_count   int(11),
level2_count   int(11),
level3_count   int(11),
wfxw_count    int(11),
max_wfjfs     int(11),
avg_wfjfs    float,
wfjfs_count  int(11),
max_fkje   int(11),
avg_fkje   double,
fkje_count  int(11),
max_znj   double,
avg_znj   double,
znj_count double,
qzcs   int(11),
cqts    int(11),
sfty   int(11),
qbzr   int(11),
zyzr   int(11),
tdzr   int(11),
cyzr   int(11),
myzr   int(11),
wfrd   int(11),
swrs   int(11),
szrs   int(11),
zsrs   int(11),
qsrs   int(11),
zjccss  double,
level  tinyint,
label  tinyint
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



create table zc_driver_matrix(
sfzh  varchar(50),
jl_1  tinyint,
jl_2  tinyint,
jl_3  tinyint,
jl_4  tinyint,
jl_5  tinyint,
zt_1  tinyint,
zt_2  tinyint,
zt_3  tinyint,
zt_4  tinyint,
ryzt_1  tinyint,
ryzt_2  tinyint,
wfxw_1  tinyint,
wfxw_2  tinyint,
wfxw_3  tinyint,
wfxw_4  tinyint,
level1_1  tinyint,
 level1_2  tinyint,
 level1_3  tinyint,
 level1_4  tinyint,
 level1_5  tinyint,
level1_6  tinyint,
level2_1  tinyint,
level2_2  tinyint,
level2_3  tinyint,
level2_4  tinyint,
level3_1  tinyint,
level3_2  tinyint,
level3_3  tinyint,
wfxwc_1  tinyint,
wfxwc_2  tinyint,
wfxwc_3  tinyint,
wfxwc_4  tinyint,
wfxwc_5  tinyint,
wfxwc_6  tinyint,
wfjfs_m1  tinyint,
wfjfs_m2  tinyint,
wfjfs_m3  tinyint,
wfjfs_a1  tinyint,
wfjfs_a2  tinyint,
wfjfs_a3  tinyint,
wfjfs_c1  tinyint,
wfjfs_c2  tinyint,
wfjfs_c3  tinyint,
wfjfs_c4  tinyint,
fkje_m1  tinyint,
fkje_m2  tinyint,
fkje_m3  tinyint,
fkje_m4  tinyint,
fkje_m5  tinyint,
fkje_m6  tinyint,
fkje_a1  tinyint,
fkje_a2  tinyint,
fkje_a3  tinyint,
fkje_a4  tinyint,
fkje_a5  tinyint,
fkje_a6  tinyint,
fkje_c1  tinyint,
fkje_c2  tinyint,
fkje_c3  tinyint,
fkje_c4  tinyint,
fkje_c5  tinyint,
znj_m1  tinyint,
znj_m2  tinyint,
znj_m3  tinyint,
znj_m4  tinyint,
znj_m5  tinyint,
znj_a1  tinyint,
znj_a2  tinyint,
znj_a3  tinyint,
znj_a4  tinyint,
znj_c1  tinyint,
znj_c2  tinyint,
znj_c3  tinyint,
znj_c4  tinyint,
znj_c5  tinyint,
qzcs_1  tinyint,
qzcs_2  tinyint,
qzcs_3  tinyint,
cqts_1  tinyint,
cqts_2  tinyint,
cqts_3  tinyint,
cqts_4  tinyint,
cqts_5  tinyint,
sfty_1  tinyint,
sfty_2  tinyint,
qbzr_1  tinyint,
qbzr_2  tinyint,
qbzr_3  tinyint,
zyzr_1  tinyint,
zyzr_2  tinyint,
zyzr_3  tinyint,
tdzr_1  tinyint,
tdzr_2  tinyint,
tdzr_3  tinyint,
cyzr_1  tinyint,
cyzr_2  tinyint,
cyzr_3  tinyint,
myzr_1  tinyint,
myzr_2  tinyint,
wfrd_1  tinyint,
wfrd_2  tinyint,
wfrd_3  tinyint,
swrs_1  tinyint,
swrs_2  tinyint,
szrs_1  tinyint,
szrs_2  tinyint,
zsrs_1  tinyint,
zsrs_2  tinyint,
zsrs_3  tinyint,
qsrs_1  tinyint,
qsrs_2  tinyint,
qsrs_3  tinyint,
qsrs_4  tinyint,
ccss_1  tinyint,
ccss_2  tinyint,
ccss_3  tinyint,
ccss_4  tinyint,
ccss_5  tinyint
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

create table zc_feature_woe(
jl_1  decimal(10,5),
jl_2  decimal(10,5),
jl_3  decimal(10,5),
jl_4  decimal(10,5),
jl_5  decimal(10,5),
zt_1  decimal(10,5),
zt_2  decimal(10,5),
zt_3  decimal(10,5),
zt_4  decimal(10,5),
ryzt_1  decimal(10,5),
ryzt_2  decimal(10,5),
wfxw_1  decimal(10,5),
wfxw_2  decimal(10,5),
wfxw_3  decimal(10,5),
wfxw_4  decimal(10,5),
level1_1  decimal(10,5),
 level1_2  decimal(10,5),
 level1_3  decimal(10,5),
 level1_4  decimal(10,5),
 level1_5  decimal(10,5),
level1_6  decimal(10,5),
level2_1  decimal(10,5),
level2_2  decimal(10,5),
level2_3  decimal(10,5),
level2_4  decimal(10,5),
level3_1  decimal(10,5),
level3_2  decimal(10,5),
level3_3  decimal(10,5),
wfxwc_1  decimal(10,5),
wfxwc_2  decimal(10,5),
wfxwc_3  decimal(10,5),
wfxwc_4  decimal(10,5),
wfxwc_5  decimal(10,5),
wfxwc_6  decimal(10,5),
wfjfs_m1  decimal(10,5),
wfjfs_m2  decimal(10,5),
wfjfs_m3  decimal(10,5),
wfjfs_a1  decimal(10,5),
wfjfs_a2  decimal(10,5),
wfjfs_a3  decimal(10,5),
wfjfs_c1  decimal(10,5),
wfjfs_c2  decimal(10,5),
wfjfs_c3  decimal(10,5),
wfjfs_c4  decimal(10,5),
fkje_m1  decimal(10,5),
fkje_m2  decimal(10,5),
fkje_m3  decimal(10,5),
fkje_m4  decimal(10,5),
fkje_m5  decimal(10,5),
fkje_m6  decimal(10,5),
fkje_a1  decimal(10,5),
fkje_a2  decimal(10,5),
fkje_a3  decimal(10,5),
fkje_a4  decimal(10,5),
fkje_a5  decimal(10,5),
fkje_a6  decimal(10,5),
fkje_c1  decimal(10,5),
fkje_c2  decimal(10,5),
fkje_c3  decimal(10,5),
fkje_c4  decimal(10,5),
fkje_c5  decimal(10,5),
znj_m1  decimal(10,5),
znj_m2  decimal(10,5),
znj_m3  decimal(10,5),
znj_m4  decimal(10,5),
znj_m5  decimal(10,5),
znj_a1  decimal(10,5),
znj_a2  decimal(10,5),
znj_a3  decimal(10,5),
znj_a4  decimal(10,5),
znj_c1  decimal(10,5),
znj_c2  decimal(10,5),
znj_c3  decimal(10,5),
znj_c4  decimal(10,5),
znj_c5  decimal(10,5),
qzcs_1  decimal(10,5),
qzcs_2  decimal(10,5),
qzcs_3  decimal(10,5),
cqts_1  decimal(10,5),
cqts_2  decimal(10,5),
cqts_3  decimal(10,5),
cqts_4  decimal(10,5),
cqts_5  decimal(10,5),
sfty_1  decimal(10,5),
sfty_2  decimal(10,5),
qbzr_1  decimal(10,5),
qbzr_2  decimal(10,5),
qbzr_3  decimal(10,5),
zyzr_1  decimal(10,5),
zyzr_2  decimal(10,5),
zyzr_3  decimal(10,5),
tdzr_1  decimal(10,5),
tdzr_2  decimal(10,5),
tdzr_3  decimal(10,5),
cyzr_1  decimal(10,5),
cyzr_2  decimal(10,5),
cyzr_3  decimal(10,5),
myzr_1  decimal(10,5),
myzr_2  decimal(10,5),
wfrd_1  decimal(10,5),
wfrd_2  decimal(10,5),
wfrd_3  decimal(10,5),
swrs_1  decimal(10,5),
swrs_2  decimal(10,5),
szrs_1  decimal(10,5),
szrs_2  decimal(10,5),
zsrs_1  decimal(10,5),
zsrs_2  decimal(10,5),
zsrs_3  decimal(10,5),
qsrs_1  decimal(10,5),
qsrs_2  decimal(10,5),
qsrs_3  decimal(10,5),
qsrs_4  decimal(10,5),
ccss_1  decimal(10,5),
ccss_2  decimal(10,5),
ccss_3  decimal(10,5),
ccss_4  decimal(10,5),
ccss_5  decimal(10,5)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


create table zc_logic_result(
jl    float,
zt   float,
ryzt   float,
max_wfxw   float,
level1_count   float,
level2_count   float,
level3_count   float,
wfxw_count    float,
max_wfjfs     float,
avg_wfjfs    float,
wfjfs_count  float,
max_fkje   float,
avg_fkje   float,
fkje_count  float,
max_znj   float,
avg_znj   float,
znj_count float,
qzcs   float,
cqts    float,
sfty   float,
qbzr   float,
zyzr   float,
tdzr   float,
cyzr   float,
myzr   float,
wfrd   float,
swrs   float,
szrs   float,
zsrs   float,
qsrs   float,
zjccss  float
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

create table zc_weight_result(
sfzh   varchar(50),
jl    float,
zt   float,
ryzt   float,
max_wfxw   float,
level1_count   float,
level2_count   float,
level3_count   float,
wfxw_count    float,
max_wfjfs     float,
avg_wfjfs    float,
wfjfs_count  float,
max_fkje   float,
avg_fkje   float,
fkje_count  float,
max_znj   float,
avg_znj   float,
znj_count float,
qzcs   float,
cqts    float,
sfty   float,
qbzr   float,
zyzr   float,
tdzr   float,
cyzr   float,
myzr   float,
wfrd   float,
swrs   float,
szrs   float,
zsrs   float,
qsrs   float,
ccss  float
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

create table zc_score_result(
sfzh    varchar(50),
score   double
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

create table zc_level_result(
sfzh    varchar(50),
score   double,
level   tinyint
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

create table zc_level_result(
sfzh    varchar(50),
score   double,
level   tinyint
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `t_elec_credit_info` (
  `id` mediumint(36) NOT NULL AUTO_INCREMENT,
  `sfzhm` varchar(30) DEFAULT NULL COMMENT '身份证号',
  `jf` varchar(10) DEFAULT NULL COMMENT '分数',
  `jb` varchar(10) DEFAULT NULL COMMENT '级别',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='我的信用信息记录表';

create table zc_black_table(
sfzh    varchar(50),
black_mark   tinyint
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;